name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x
      - run: npm run install
      - run: npm run format:check
      - run: npm run type-check
      - run: npm run test:ci
      - run: npm run build
